cleanup v1.6 LTS
conda-forge/julia-feedstock pull request #159
Opened 2021-12-26 19:27 UTC by ngam

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2021-12-26 19:27 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-12-26 19:31 UTC, ngam commented
@conda-forge-admin, please rerender

2021-12-27 18:49 UTC, ngam commented
@conda-forge-admin, please restart ci

2021-12-28 02:23 UTC, ngam commented
@conda-forge-admin, please restart ci

2021-12-28 02:23 UTC, ngam commented
@conda-forge-admin, please rerender

2021-12-29 03:53 UTC, ngam commented
Closing this as it we don't want to introduce any breaking changes.

2022-01-03 10:14 UTC, mkitti commented
We probably should still merge this, but with a commented out activate.sh as in cfc88fd. This should result in no breakage if someone has already been working with a Julia depot in `~/.julia`. If people want the new depot behavior with 1.6.x, they can uncomment the appropriate lines containing `export`.

@ngam, could you backport the other commits?

2022-01-03 16:12 UTC, ngam commented
Sure, we should do that, but let's give people a week or two to weigh in. Copying @zklaus.

2022-01-03 17:49 UTC, ngam commented
@mkitti yes I will attend to this soon

2022-01-05 19:30 UTC, mkitti commented on recipe/build.sh
> +
This still needs to be removed

2022-01-05 19:31 UTC, mkitti commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="A conda-forge release: https://github.com/conda-forge/julia-feedstock" \
I notice that wraps in my 80 character wide console. Perhaps we should shorten this somehow? Just include the URL?

2022-01-05 19:32 UTC, ngam commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="A conda-forge release: https://github.com/conda-forge/julia-feedstock" \
Yes. I was thinking about the same :)

2022-01-05 19:32 UTC, ngam commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="A conda-forge release: https://github.com/conda-forge/julia-feedstock" \
How about this?

2022-01-05 19:34 UTC, ngam commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="A conda-forge release: https://github.com/conda-forge/julia-feedstock" \
`By conda-forge: github.com/conda-forge/julia-feedstock` = 54

`A conda-forge release: https://github.com/conda-forge/julia-feedstock` = 69

2022-01-05 19:49 UTC, ngam commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="A conda-forge release: https://github.com/conda-forge/julia-feedstock" \
For comparison:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
 _/ |\__'_|_|_|\__'_|  |  By conda-forge: github.com/conda-forge/julia-feedstock
 _/ |\__'_|_|_|\__'_|  |  A conda-forge release: https://github.com/conda-forge/julia-feedstock
 _/ |\__'_|_|_|\__'_|  |  github.com/conda-forge/julia-feedstock

|__/                   |

julia> 

```

2022-01-05 23:31 UTC, mkitti requested changes
Also this fixes the 1.6 branch. I have not checked what openlibm version Julia 1.6.5 uses.

2022-01-05 23:31 UTC, mkitti commented on recipe/build.sh
> +export JULIA_SSL_CA_ROOTS_PATH=$CONDA_PREFIX/ssl/cacert.pem
This is needed at runtime via activate.sh, not build time.

2022-01-05 23:31 UTC, mkitti commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="By github.com/conda-forge/julia-feedstock" \
Does https:// fit here? Without that, my terminal does not recognize the URL.

2022-01-05 23:35 UTC, ngam commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="By github.com/conda-forge/julia-feedstock" \
> Also this fixes the 1.6 branch. I have not checked what openlibm version Julia 1.6.5 uses.

Should be something in the v0.7.x range. Everything was fine and stable until the v0.8.0 release.

2022-01-05 23:35 UTC, ngam commented on recipe/build.sh
> + TAGGED_RELEASE_BANNER="By github.com/conda-forge/julia-feedstock" \
> Does https:// fit here? Without that, my terminal does not recognize the URL.

Will change :)

2022-01-05 23:35 UTC, ngam commented on recipe/build.sh
> +export JULIA_SSL_CA_ROOTS_PATH=$CONDA_PREFIX/ssl/cacert.pem
Ooops sorry

2022-01-05 23:41 UTC, ngam commented
> Also this fixes the 1.6 branch. I have not checked what openlibm version Julia 1.6.5 uses.

https://github.com/JuliaLang/julia/blob/96a99c268a96ee61f6ff8fe4c2d53208f0cb042a/deps/Versions.make#L86-L89

2022-01-05 23:54 UTC, ngam commented
> > Also this fixes the 1.6 branch. I have not checked what openlibm version Julia 1.6.5 uses.
> 
> https://github.com/JuliaLang/julia/blob/96a99c268a96ee61f6ff8fe4c2d53208f0cb042a/deps/Versions.make#L86-L89
> 
> V0.7.3 --- submitting a build for that. But generally, the differences between the 0.7.x builds are very minor. That's partly why hard pinning is discouraged --- why pin so hard if you can be relax stuff? Upstream should relax their pinnings and give ranges, rather than exact pinning. Oh I forgot ... they vendor it all... 🤣

update: not going to build v0.7.3 --- will require a significant patch to work:

https://github.com/JuliaMath/openlibm/compare/v0.7.3...v0.7.4

2022-01-06 03:15 UTC, merged

2022-01-07 09:17 UTC, SylvainCorlay commented
This appears to cause some breakage downstream.

Julia is looking for `PREFIX/lib/julia/libopenlibm.so` (or dylib) at runtime and not finding it.

2022-01-07 09:18 UTC, SylvainCorlay commented
Logs of a failing CI build downstream: https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/432647/logs/14

2022-01-07 10:46 UTC, SylvainCorlay commented
Thanks, it seems to be fixed with the newest build indeed.

2022-01-07 12:37 UTC, SylvainCorlay commented
@mkitti I am seeing the latest build of Julia segfault when doing `Pkg.install`.

https://pipelines.actions.githubusercontent.com/9zddvhQiTJbR8A2Iyvzp5LUMYExviz48Jr6OTWD1xGufbW56YS/_apis/pipelines/1/runs/155/signedlogcontent/3?urlExpires=2022-01-07T12%3A37%3A33.4425814Z&urlSigningMethod=HMACV1&urlSignature=YZJdgN3OwdanhBkm0ksqStE13572V2U2R4OGEmyR1qM%3D

2022-01-07 13:57 UTC, mkitti commented
The segfaults are occurring in libcurl ... and 7.81 was just released on conda-forge.